version: '3.8'

services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_PASSWORD=897f333d10050fc7e54f49ac8596081e
    ports:
      - "5432:5432"
    expose:
      - 5432

  minio:
    image: bitnami/minio:2023.7.18
    ports:
      - "9000:9000"
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: "minio-access-key"
      MINIO_ROOT_PASSWORD: "minio-secret-key"
      MINIO_DEFAULT_BUCKETS: "minio-default-bucket"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      MINIO_URL: http://minio:9000
      DEV_PANEL_ENABLED: false
      META_DIRECTORY: classpath*:meta
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    expose:
      - 8080

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    ports:
      - "8081:8081"
    expose:
      - 8081
